# QGEP customization template file

qgis_bin: ${HOME}/opt/QGIS2/build/output/bin/qgis
output_project: ${HOME}/Documents/QGEP/sige/qgis-project/qgep_sige_auto.qgs

style_file: ${HOME}/Documents/QGEP/sige/qgis-project/styles/qgep.style

srid: 2056

map_center:
  x: 2559858
  y: 1144177

background_layers:
  - file: /home/drouzaud/Documents/QGEP/sige/cadastre/cadastre_pg.qgs
    group: Fonds de plans

quickfinder: ./qgep_sige.qfts
